fossology/FOSSologyUI

src/components/Header/index.js, src/pages/Help/Overview/index.js
Updated the entities in overview page with plain text and updated the navbar other items to display only when user is authenticated.
- Updated the overview page.
- Added the condition in Header component.
Visit `/` route.
=> fix(ui): replaced entities and updated the navbar

src/components/Widgets/Button/index.js, src/pages/Home/index.js, src/styles/globalStyle.js
Added the separate button widget related to our theme and replaced the react-bootstrap button with our custom component.
- Added the button widget insde components.
- Fix the login button style
Visit to the `/` route
=> feat(widget): added the Button widget and fixed the login button

.github/workflows/test.yml, src/App.test.js, src/__snapshots__/App.test.js.snap
Currently there are no GitHub actions test for Pull Requests. Hence, added GitHub actions for CI/CD test.
- Added `test.yml` file
Check if GitHub actions are running on every push and pull request to master and development branch
=> feat(CI/CD): add github actions for CI/CD test

.dockerignore, Dockerfile, README.md
Added the Dockerfile (alternative method) for installation.
- Added the Dockerfile.
- Updated the installation method in README.
Run the following commands mentioned in the README
=> feat(docker): added the Dockerfile and updated the readme

src/components/Header/index.js, src/constants/routes.js, src/pages/Organize/Folder/Create/index.js, src/pages/Organize/Folder/Delete/index.js, src/pages/Organize/Folder/Edit/index.js, src/pages/Organize/Folder/Move/index.js, src/pages/Organize/Uploads/Delete/index.js, src/pages/Organize/Uploads/Edit/index.js, src/pages/Organize/Uploads/Move/index.js, src/styles/globalStyle.js
Added the sub dropdowns and updated the background color with our theme colours.
- Updated the header.
- Updated the dropdown with theme colour.
=> feat(ui): fixed the dropdown styles and added the sub-dropdown

src/App.js, src/components/Header/index.js, src/context/index.js, src/shared/storageHelper.js, src/styles/globalStyle.js, src/styles/theme.js
Added the team toggle functionality in the navbar.
- Created the context for the global state maintenance.
- Added the light and dark theme option in Header.
Check the header and toggle between the themes.
=> feat(theme): added the custom theme functionality in the navbar

src/Routes.js, src/api/search.js, src/constants/endpoints.js, src/pages/Search/index.js, src/services/search.js, src/shared/helper.js
Added the Search page
- Added the input container in the widgets. 
- Added the search mechanism.
Visit the `/search` page
=> feat(search): added the search page

src/components/Widgets/Alert/index.js, src/components/Widgets/Tooltip/index.js, src/pages/Home/index.js
Added the widget for Alerts and Tooltip.
- Created the custom component for Alert and Tooltip.
- Replaced the login alert with the custom component.
- Added the hover and focus property on Button.
Closes #44
=> feat(ui): added the custom component for alert and tooltip

src/api/users.js, src/components/Header/index.js, src/pages/Home/index.js, src/services/users.js, src/shared/authHelper.js
Added username in dropdown
- Added username in dropdown
- Integrated `/users/self` API
- Updated the `isAuth` and `logout` functions
After login click on user icon to verify the screenshot
=> feat(user): add username in dropdown and integrate users/self api

src/Routes.js, src/api/folders.js, src/components/Widgets/Input/index.js, src/pages/Home/index.js, src/pages/Organize/Folder/Delete/index.js, src/services/folders.js
Added Delete folder page
- Added Delete folder page
Go to `http://localhost:3000/organize/folders/delete`
=> feat(folder): add delete folder page

src/Routes.js, src/api/folders.js, src/pages/Organize/Folder/Create/index.js, src/pages/Organize/Folder/Delete/index.js, src/services/folders.js
Added Create new folder page
- Added Create new folder page
- Added get all folder API
- Added create folder API
- Updated input component for using select list
Go to `http://localhost:3000/organize/folders/create`
=> feat(folder): add create folder page

src/Routes.js, src/api/folders.js, src/constants/endpoints.js, src/pages/Organize/Folder/Edit/index.js, src/services/folders.js
Added Edit folder page
- Added Edit folder page
Go to `http://localhost:3000/organize/folders/edit`
=> feat(folder): add edit folder page

src/components/Widgets/Input/index.js, src/pages/Search/index.js
Fixed search page
- Added error check in search page
- Added alert popup with error message
- Removed duplicate CSS Ids
- Added loading spinner on button
- Fixed the input widget to use id
Go to `http://localhost:3000/search`
=> fix(search): add error check and fix duplicate ids

src/Routes.js, src/api/folders.js, src/constants/endpoints.js, src/pages/Organize/Folder/Create/index.js, src/pages/Organize/Folder/Delete/index.js, src/pages/Organize/Folder/Edit/index.js, src/pages/Organize/Folder/Move/index.js, src/services/folders.js
Added move upload or folder
- Added move upload or folder
Go to `http://localhost:3000/organize/folders/move`
=> feat(folder): add move upload or folder

src/Routes.js, src/pages/Jobs/AllJobs/index.js, src/pages/Jobs/MyRecentJobs/index.js, src/pages/Jobs/ScheduleAgents/index.js, src/pages/Organize/Folder/Create/index.js, src/pages/Organize/Folder/Delete/index.js, src/pages/Organize/Folder/Edit/index.js, src/pages/Organize/Folder/Move/index.js, src/pages/Organize/License/index.js, src/pages/Organize/Uploads/Edit/index.js, src/pages/Organize/Uploads/Move/index.js, src/pages/Upload/File/index.js, src/pages/Upload/ImportReport/index.js, src/pages/Upload/Server/index.js, src/pages/Upload/Url/index.js, src/pages/Upload/Vcs/index.js
Added all the pages for the routes and linked them.
- Created the pages for all the routes.
- Linked all the routes in Routes.js.
***Note: Most of the conflicts happened in Routes.js and routes js is not even well structured.***
Visit to all the routes.
https://fossology-ui.netlify.app/
=> fix(routes): added the routes for all pages

src/pages/Organize/Folder/Create/index.js, src/pages/Organize/Folder/Delete/index.js, src/pages/Organize/Folder/Edit/index.js, src/pages/Organize/Folder/Move/index.js, src/pages/Search/index.js, src/pages/Upload/File/index.js
Updated all the alerts.
- Changed all the alerts with our custom component instead of React bootstrap component.
Visit to all the routes.
=> fix(alert): updated all the alerts with custom components

src/components/Upload/CommonFields/AccessLevel/index.js, src/components/Upload/CommonFields/IgnoreScm/index.js, src/components/Upload/CommonFields/LicenseDecider/index.js, src/components/Upload/CommonFields/UploadReuse/index.js, src/components/Widgets/Tooltip/index.js
Added the additional information for the components.
=> feat(tooltip): added the extra information

src/pages/Help/Overview/index.js, src/pages/Organize/Folder/Move/index.js, src/pages/Search/index.js
Fix #63 
- Added the fossology website target attribute.
- updated the Mode Folder title.
- updated the styling of search page.
visit to `/search`, `/help/overview` , `/organize/folders/move`
=> fix(ui): fixed the bugs in search, overview, create folder page

src/api/sendRequest.js
Currently when a user token is revoked from backend before the cookie expire, then the user should be logged out from frontend.
- Updated the sendrequest.js file to logout the user in case of any unauthorized access request
Login with your credentials in frontend.
Revoke the generated token from backend.
On page reload user will be logged out from frontend
=> fix(auth): logout user when token is revoked

src/components/Widgets/Alert/index.js
Updated the alerts styling to snackbars.
closes #78 
- Changed the file of Alert in the Widgets.
*Note: We don't need to modify any pr or existing code changed the styling of the widget*
Test all the popups.
=> feat(snackbar): updated the alerts to snackbar

src/Routes.js, src/pages/Organize/Folder/Unlink/index.js
Added unlink upload or folder
- Added unlink upload or folder
Go to `http://localhost:3000/organize/folders/unlinkContent`
=> feat(folder): add unlink upload or folder

src/Routes.js, src/api/groups.js, src/components/Header/index.js, src/constants/endpoints.js, src/constants/routes.js, src/pages/Admin/Group/Create/index.jsx, src/pages/Organize/Uploads/Move/index.js, src/services/groups.js, src/shared/authHelper.js
Added create group page
- Added create group page
- Updated Header to display Admin section in Navbar only for admin users
Go to `http://localhost:3000/admin/groups/create`
=> feat(group): add create group page

src/Routes.js, src/api/users.js, src/components/Header/index.js, src/constants/endpoints.js, src/constants/routes.js, src/pages/Admin/Users/Delete/index.jsx, src/services/users.js, src/shared/authHelper.js
Added delete users page
- Added delete users page
Go to `localhost:3000/admin/users/delete`
=> feat(user): add delete user page

src/api/browse.js, src/components/Upload/CommonFields/OptionalAnalysis/index.js, src/components/Upload/CommonFields/index.js, src/constants/endpoints.js, src/pages/Jobs/ScheduleAgents/index.js
Added schedule analysis page
- Added schedule analysis page
- Updated browse api to use `query-string` library to sanitize url query
Go to `http://localhost:3000/jobs/scheduleAgents`
=> feat(jobs): add schedule analysis page

src/Routes.js, src/shared/AdminLayout.js, src/shared/authHelper.js
Added admin layout component
- Created a new auth gaurd for admin pages which checks whether the user is admin or not. If not it redirects to homepage.
=> feat(layout): add admin layout for admin pages

src/api/sendRequest.js, src/constants/auth.js, src/pages/Browse/index.css, src/pages/Browse/index.js, src/pages/Organize/Uploads/Move/index.js, src/services/browse.js
Added the pagination feature in browse page.
- Added the entries field.
- Added the pagination just like the current implementation.
- Stored the response header of x-total-pages in localStorage.
Visit to `/browse`
=> feat(browse-pagination): Added the browse pagination feature

src/pages/Jobs/ScheduleAgents/index.js, src/pages/Upload/File/index.js, src/shared/storageHelper.js
Use scan preference from user object. Closes: #88 
- Updated code to use scan preference from local storage
Check schedule analysis page and upload from file page
=> fix(agents): use agent preference from local storage

src/__snapshots__/App.test.js.snap, src/components/Header/index.js, src/styles/global.css
Earlier on small screen size, the user icon dropdown was not displayed. Fixed it to now display dropdown on small screen as well.
- Fixed header on small screen size
Test Header for screen size smaller than 991px.
=> fix(header): fix header on small screen size

package.json, src/App.js, src/components/TreeContainer/index.css, src/components/TreeContainer/index.js, src/pages/Browse/index.js, yarn.lock
Added folder navigation tree view 
- Added unlink upload or folder
Go to `http://localhost:3000/browse`
=> feat(folder-navigation): add folder tree view

src/api/sendRequest.js, src/api/upload.js, src/constants/endpoints.js, src/pages/Upload/Vcs/index.js, src/services/upload.js
Added the vcs upload page.
- added the recursive request for the request of `/uploads/{id}`, retries is set to be for 10 now.
visit to `/uploads/vcs`
=> feat(vcs): added the upload vcs page

src/pages/Browse/index.js
Fix typo on browse page
- Fixed Navigation spelling
Go to browse page
=> fix(typo): fix typo on browse page

.github/workflows/deploy.yml
When a merge happens to main branch, deploy to GitHub pages.
1. New workflow file `deploy.yml` to deploy to Github pages.
=> feat(cd): Deploy to GitHub pages

.env.sample, src/constants/auth.js
Added the auth variables in env
closes #105
=> feat(env): added the auth variables in env

.github/workflows/deploy.yml, src/Routes.js
Currently the blank screen is coming to https://fossology.github.io/FOSSologyUI/ 
Added the public url to `deploy.yml`
=> fix(gh-pages): added the public url

src/components/TreeContainer/index.jsx, src/components/Upload/CommonFields/index.jsx, src/components/Widgets/Input/index.jsx, src/pages/Browse/index.jsx, src/pages/Jobs/ScheduleAgents/index.jsx, src/pages/Organize/Uploads/Delete/index.jsx
Closes #99 
Fixed warnings on 
- browse page
- job schedule page
- delete upload page
- input container component
See console on different pages
- warnings on browse page due to the use `react-virtualized-tree` library
- warnings on about page. (Need to discuss whether it is generated from some source or we are allowed to edit this file html)
=> Fix(warnings): fix console warnings 

src/components/Header/index.jsx, src/constants/externalLinks.js, src/constants/routes.js, src/pages/Help/About/index.jsx
Updated links to keep external links in externalLinks.js file and internal links in routes object.
- Forbid full page reload on fossology image on Header
- Added licenseCSV link in routes object
- Keep external links on About page in externalLinks.js file
Test updated links
=> fix(links): keep external links in externalLinks.js file

src/shared/AdminLayout.jsx, src/shared/PrivateLayout.jsx, src/shared/PublicLayout.jsx
Update absolute import to relative in layout component
- Updated Public, Private and Admin layout component
Go to `localhost:3000`
=> fix(imports): Update absolute import to relative in layout component

src/__snapshots__/App.test.jsx.snap, src/api/auth.js, src/api/browse.js, src/api/groups.js, src/api/licenses.js, src/api/organizeUploads.js, src/api/search.js, src/api/sendRequest.js, src/api/upload.js, src/api/users.js, src/components/Header/index.jsx, src/components/Widgets/TextIcon/index.jsx, src/pages/Browse/index.jsx, src/pages/Home/index.jsx, src/pages/Jobs/ScheduleAgents/index.jsx, src/pages/Organize/License/index.jsx, src/pages/Organize/Uploads/Delete/index.jsx, src/pages/Organize/Uploads/Edit/index.jsx, src/pages/Organize/Uploads/Move/index.jsx, src/pages/Search/index.jsx, src/pages/Upload/Vcs/index.jsx, src/services/groups.js, src/services/organizeUploads.js, src/shared/AdminLayout.jsx, src/shared/authHelper.js, src/shared/helper.js
Created user group dropdown. Closes #90 
- Created reusable text icon component
- Updated login mechanism to fetch group list on login
- Saved the group list in local storage for quick access 
- Displayed group list on header as a dropdown
- Ensured font to use colour based on current active theme
Check header
=> feat(user-group): display user group in dropdown

src/api/sendRequest.js, src/pages/Admin/License/Create/index.jsx, src/pages/Upload/File/index.jsx, src/pages/Upload/Vcs/index.jsx
Vcs page is getting broken on making the request.
- Changes the promise rejection parameter.
- Change the retries left to the same property in sendrequest.
- Return the function if retries are greater than 0.
Visit to `/upload/vcs`
Closes #111
=> fix(vcs): fixed the upload vcs page

.eslintrc.json, src/__snapshots__/App.test.jsx.snap, src/api/groups.js, src/components/Header/index.jsx, src/styles/globalStyle.js, src/styles/theme.js
Added the active class to nav-items and changed the dropdown item colour to the theme primary colour instead of bootstrap primary colour.
- Added the secondary colour to the theme.js for the darker shade of active element.
- Added the `active-nav-item` and `dropdown-item:hover` in the globalStyle.js
- Added the location for the paths in header component.
- Added the `import-parse` property in .eslintrc to resolve the parsing errors.
- Fixed the groups api function by removing credentials which is defined in sendRequest.
=> feat(active-navbar): added the active class to nav items

src/api/browse.js, src/api/search.js, src/api/upload.js, src/pages/Jobs/ScheduleAgents/index.jsx, src/pages/Organize/Uploads/Edit/index.jsx, src/pages/Upload/File/index.jsx, src/pages/Upload/Vcs/index.jsx, src/services/browse.js, src/services/search.js, src/services/upload.js
Please describe the changes in your pull request in few words here.
List the changes done to fix a bug or introducing a new feature.
Describe the steps required to test the changes proposed in the pull request.
=> fix(api): sanitize the names of api functions

src/pages/Upload/Server/index.jsx
Added the upload server page.
- Added the upload server page.
- Added the required state variables for it.
*Note: Currently, upload from server api is unavailable, that is need to be discussed in meeting*
Visit to `/upload/server`
=> feat(upload-server): added the upload server page

scripts/copyrightsScript.js, src/pages/Admin/Users/Delete/index.jsx, src/pages/Organize/Folder/Create/index.jsx, src/pages/Organize/Folder/Delete/index.jsx, src/pages/Organize/Folder/Edit/index.jsx, src/pages/Organize/Folder/Move/index.jsx, src/pages/Organize/Folder/Unlink/index.jsx, src/pages/Organize/Uploads/Edit/index.jsx, src/pages/Organize/Uploads/Move/index.jsx, src/pages/Upload/File/index.jsx, src/pages/Upload/Vcs/index.jsx, src/services/browse.js, src/shared/authHelper.js, src/shared/helper.js
Reduced duplicate code by using reusable function.
- Added reusable function for error handling
- Fixed eslint warnings in copyright script 
Go to `localhost:3000`
=> refactor(handleError): add reusable function for error handling

src/pages/Upload/Vcs/index.jsx
fixed the analysis options in vcs.
Added the defaultAgentsList function instead of hard coded analysis options.
Vist to `/upload/vcs`
=> fix(vcs): fixed the analysis of scanData

src/pages/Organize/Uploads/Move/index.jsx
No fallback condition is there if no upload is selected in move or copy.
- Added the condition for move upload and copy upload.
- Added the spinner in buttons.
=> fix(uplods-move-copy): added the fallback condition

src/components/TreeContainer/index.css, src/components/TreeContainer/index.jsx, src/pages/Browse/index.jsx
Added the browsing of uploads with folders.
Closes #131 
- Added the handleClick function for the folders browsing.
Visit to `/browse`
=> feat(browse): added the browsing of uploads with folders

src/api/upload.js, src/components/Upload/CommonFields/AccessLevel/index.jsx, src/components/Upload/CommonFields/IgnoreScm/index.jsx, src/components/Upload/CommonFields/LicenseDecider/index.jsx, src/components/Upload/CommonFields/OptionalAnalysis/index.jsx, src/pages/Upload/Server/index.jsx, src/pages/Upload/Url/index.jsx, src/pages/Upload/Vcs/index.jsx, src/services/upload.js
Added the upload from url page.
Visit to `/upload/url`
=> feat(url): added the upload from url page

src/api/search.js, src/pages/Search/index.jsx, src/services/search.js
Added the pagination in search page.
Since new api exposed the pages and limit param so that was updated in search page.
Visit to `/search`
=> feat(search): added the pagination in search page

src/api/sendRequest.js, src/components/Header/index.jsx, src/pages/Jobs/ScheduleAgents/index.jsx, src/pages/Upload/File/index.jsx, src/pages/Upload/Server/index.jsx, src/pages/Upload/Vcs/index.jsx
use default group returned from `/users/self` API
- Updated the default group from "fossy" to the value returned from API
Verify default group
=> feat(group): use default group returned from API

src/shared/helper.js
Add null check in name initials function
- Updated name initials function
=> fix(nameInitials): add null check in name initials function

src/components/Header/index.jsx, src/services/users.js, src/styles/globalStyle.js
Highlighted the currently selected group in the navbar
- Updated the background colour of the active group
Change group name from the navbar
=> fix(highlight-group): highlight the current selected group

src/__snapshots__/App.test.jsx.snap, src/pages/Home/style.js
Added border to login form in dark theme
- Updated style to use border colour based on the current theme
Visit login page in dark theme
=> fix(login-form): add border to form in dark theme 

src/components/Widgets/Alert/index.jsx, src/pages/Admin/Group/Create/index.jsx, src/pages/Admin/Users/Delete/index.jsx, src/pages/Browse/index.jsx, src/pages/Home/index.jsx, src/pages/Jobs/ScheduleAgents/index.jsx, src/pages/Organize/Folder/Create/index.jsx, src/pages/Organize/Folder/Delete/index.jsx, src/pages/Organize/Folder/Edit/index.jsx, src/pages/Organize/Folder/Move/index.jsx, src/pages/Organize/Folder/Unlink/index.jsx, src/pages/Organize/License/CandidateLicense/index.jsx, src/pages/Organize/License/Create/index.jsx, src/pages/Organize/Uploads/Delete/index.jsx, src/pages/Organize/Uploads/Edit/index.jsx, src/pages/Organize/Uploads/Move/index.jsx, src/pages/Search/index.jsx, src/pages/Upload/File/index.jsx, src/pages/Upload/Server/index.jsx, src/pages/Upload/Url/index.jsx, src/pages/Upload/Vcs/index.jsx, src/styles/global.css
The ui is shifting down whenever the snackbar is appearing which leads to bad user experience.
- Added the styling for keeping the snackbar fixed.
- Fixed all the pages.
- Shifted snackbar code inside main container to remove the flicker effect.
Visit all the routes.
=> fix(ui): fixed the snackbar now ui not shifting

src/__snapshots__/App.test.jsx.snap, src/components/Header/index.jsx, src/styles/globalStyle.js
Header is not fixed on the top when we scroll down the page.
- Removed the outer most `div` from header and the `overflow-x` because sticky top won't work with it.
- Added the sticky top.
=> fix(header): made the header sticky

src/__snapshots__/App.test.jsx.snap, src/components/Footer/index.jsx
fixed the footer text alignment
=> fix(footer): fixed the footer alignment

src/Routes.jsx, src/__snapshots__/App.test.jsx.snap, src/api/info.js, src/components/Footer/index.jsx, src/constants/endpoints.js, src/services/info.js, src/shared/AdminLayout.jsx, src/shared/PrivateLayout.jsx, src/shared/PublicLayout.jsx, src/shared/storageHelper.js
Use fossology version from info API. Currently using `toLocaleString()` for build date and commit date.
use fossology version from info API
See footer of any page
=> feat(fossology-version): use fossology version from info API

.eslintrc.json, src/api/jobs.js, src/api/sendRequest.js, src/components/Widgets/Input/index.jsx, src/constants/endpoints.js, src/pages/Browse/index.jsx, src/services/jobs.js, src/shared/helper.js
Added the option to export and download the report. Dependent on Shruti3004/FOSSology-REST-API#14
- Schedule report generation
- Automatically download the report when generated
Visit `http://localhost:3000/browse`
=> feat(report): add export report option on browse page

src/pages/Admin/License/Create/index.jsx, src/pages/Organize/License/Create/index.jsx, src/pages/Upload/File/index.jsx, src/pages/Upload/Server/index.jsx, src/pages/Upload/Url/index.jsx, src/pages/Upload/Vcs/index.jsx, src/styles/global.css
Fixed the textareas in all the pages, the font inside textareas are weirdly bold and their sizes are small at some places and some places has width 100%.
=> fix(ui): fixed the textareas in all the pages

src/pages/Home/__snapshots__/index.test.jsx.snap, src/pages/Home/index.jsx
Login button alignment fixed as mentioned in #175 
Changed `index.jsx`
Fixes #175 
PTAL @GMishx
=> fix(ui): login button alignment fixed

src/stories/Alert.stories.jsx, src/stories/Image.stories.jsx, src/stories/Input.stories.jsx, src/stories/TextIcon.stories.jsx, src/stories/Tooltip.stories.jsx
Added stories for [widgets](https://github.com/fossology/FOSSologyUI/tree/main/src/components/Widgets)
https://user-images.githubusercontent.com/70439799/159658216-41d4a6af-d5d3-48da-b59a-ca07ddc5582a.mp4
- Run `yarn run storybook` and see added widgets
Fixes #161
=> feat(stories): Add stories for widgets

src/components/Header/index.css, src/components/Header/index.jsx, src/components/TreeContainer/index.jsx, src/pages/Browse/index.jsx
There were design related issues in the Navbar and browse page. Below screenshots will make it more clearer.
This PR contains design fixes concerned with.
- Navbar
- Browse page
The icons were in column alignment which took more space in tablet or mobile view.
By default the height was `50rem` for the folders navigation which gave extra space for no reason and didn't looked good from ui perspective
https://user-images.githubusercontent.com/71918441/172065518-f59bd0ae-1179-4735-80ed-c87fb5b3d6a7.mov
This change contains dynamic height value assignment based on number of folders and subfolders which solves this issue.
https://user-images.githubusercontent.com/71918441/172065539-54858e6a-ce12-4a69-9e1d-cd70a3b4a2a0.mov
=> update(ui): Design related fixes (Navbar and browse page)

src/pages/Browse/index.jsx
Search function implemented in the `/browse` page
`pages/Browse/index.jsx`
Run the UI project with the backend and try to search the uploaded files in the `/browse` page
Fixes #225
=> fix(browse): search bar function implemented

src/api/jobs.js, src/pages/Jobs/AllJobs/index.jsx, src/services/jobs.js
`/allRecentJobs` page UI is completed with a table featuring dynamic search and pagination. Also with a custom number of rows.
A new package has been installed MDBreact (https://github.com/mdbootstrap/mdb-react-ui-kit)
install the updated dependencies and run the server to visit the `/allRecentJobs` page
Fixes #222 
@shaheemazmalmmd  @GMishx @ag4ums  
Please do have a look
(https://help.github.com/articles/closing-issues-using-keywords/)
=> feature(ui): `/allRecentJobs` page completed

package.json, src/pages/Jobs/AllJobs/index.jsx, src/styles/global.css, yarn.lock
Horizontal style pagination added in the `/allRecentJobs` page.
New packages have been used in this PR. Be sure to run `yarn install` when starting the project
Run `yarn install` and start the server.
Visit the `/allRecentJobs` and scroll down to see the pagination.
https://user-images.githubusercontent.com/63705023/175760990-fa73245d-14f2-4ace-a862-d9f802fa9159.mp4
=> feat(ui): horizontal pagination added in `allRecentJobs`

src/pages/Browse/index.jsx, src/pages/Jobs/AllJobs/index.jsx, src/styles/global.css
Pagination module implemented in the `/browse` page
`/pages/Browse/index.jsx`
Run the project and visit Browse page
Screenshot:
=> feat(ui): Pagination in Browse page

src/api/jobs.js, src/components/Header/index.jsx, src/constants/endpoints.js, src/pages/Jobs/AllJobs/index.jsx, src/pages/Jobs/MyRecentJobs/index.jsx, src/services/jobs.js
- All recent jobs is now only accessible  by admins ( Related with this back-end PR:  https://github.com/fossology/fossology/pull/2260 This needs to be merged first in order to avoid bugs.)
- MyRecentJobs page also implemented.
Introduced a new API endpoint and used conditions for the header.
Run compile the back-end after PR: ( https://github.com/fossology/fossology/pull/2260 ) is merged and run the server. Use Admin and non-Admin accounts to test out the jobs pages.
[Screencast from 18-07-22 01:23:54 PM IST.webm](https://user-images.githubusercontent.com/63705023/179469079-a1990390-aaf9-4958-a2d5-e34bb14271c6.webm)
Fixes #244
PTAL @GMishx @shaheemazmalmmd @Shruti3004
=> feat(ui): All jobs only accessible by admin

src/styles/global.css
Matched delay of Body with delay of Cards in Home Page #253
=> Dark mode delay Fixed #253

src/Routes.jsx, src/api/auth.js, src/api/users.js, src/components/Header/index.jsx, src/components/Upload/CommonFields/AccessLevel/index.jsx, src/components/Widgets/Input/index.jsx, src/components/Widgets/Modal/index.css, src/components/Widgets/Modal/index.jsx, src/constants/constants.js, src/constants/endpoints.js, src/constants/routes.js, src/pages/Admin/Users/Edit/index.css, src/pages/Admin/Users/Edit/index.jsx, src/pages/Admin/Users/Edit/token_space.jsx, src/services/users.js, src/utils/index.js
Ui and API Implementation of the `Edit user page`. 
Added all the UI components for the Edit user page and wrote frontend logic for data collection and better UX.
https://user-images.githubusercontent.com/71918441/184528131-2ff0e6bd-ab48-43fc-99d1-6a9d7c036268.mp4
Go to `Admin > Users > Edit User Account` to see the new UI
1. For testing changes related to modifying user details, you need to install changes from this PR 👉 : https://github.com/fossology/fossology/pull/2262
2. For testing the token apis, you need to install changes from this PR 👉 : https://github.com/fossology/fossology/pull/2266
PTAL : @Shruti3004 @GMishx @shaheemazmalmmd @sjha2048 
This closes #231 .
=> feature(ui): ui and styling for the `edit user page`
