fossology/FOSSologyUI

src/Routes.js
src/components/Widgets/Input/index.js
src/pages/Upload/ImportReport/index.js

Added the Import report page of uploads section.
- Added the report Import page.
- Added Input widget which can be used with all the pages.
***Note: Added all the state variables for the page as soon as we get the api we have to just link them.***
Visit to the route `/upload/report`

feat(importReport): added the report import page of uploads

---

src/Routes.js
src/api/getFolder.js
src/api/upload.js
src/components/Upload/CommonFields/AccessLevel/index.js
src/components/Upload/CommonFields/IgnoreScm/index.js
src/components/Upload/CommonFields/LicenseDecider/index.js
src/components/Upload/CommonFields/OptionalAnalysis/index.js
src/components/Upload/CommonFields/UploadReuse/index.js
src/components/Upload/CommonFields/index.js
src/components/Widgets/Input/index.js
src/constants/endpoints.js
src/pages/Search/index.js
src/pages/Upload/File/index.js
src/pages/Upload/Url/index.js
src/pages/Upload/Vcs/index.js
src/services/getFolder.js
src/services/upload.js
src/shared/helper.js

Added the upload file page.
- Created the separate folder for uploads in Components that contains helper functions which will get reused in VCS, Url and server.
- AccessLevel
- Ignore Scm
- License Decider
- Optional Analysis
- Upload Reuse
- Added the Upload file page
visit to the route '/upload/file'

feat(upload): added the upload file page

---

src/api/browse.js
src/api/sendRequest.js
src/components/Widgets/Input/index.js
src/constants/endpoints.js
src/pages/Browse/index.js
src/pages/Search/index.js
src/services/browse.js
src/styles/global.css

Added the Browse page prototype.
- Added the api for browse page.
- Created the layout for the browse page.
Visit to `/browse`

feat(browse): Added the prototype for the uploads page

---

src/constants/externalLinks.js
src/pages/Help/Overview/index.js

Fixed the heading on move or copy folder and updated the link of fossology website to open in new tab.
Closes #63 
- Fixed the heading on move or copy folder
- updated the link of fossology website to open in new tab in the help page
Go to `http://localhost:3000/help/overview` and `http://localhost:3000/organize/folders/move`

fix(UI): open link in new tab and fix heading

---

src/Routes.js
src/api/organizeUploads.js
src/constants/endpoints.js
src/pages/Organize/Uploads/Delete/index.js
src/services/organizeUploads.js

Added the delete Upload file page.
- Created the getFolders page from where it is fetching all the folders.
- Created the organizeUploads which contains `deleteUploadFile` and `getUploadsById`.
- Added the property for options in InputContainer.
Visit to `/organize/uploads/delete`

feat(upload): added the delete uploads page

---

src/Routes.js
src/components/Header/index.js
src/constants/routes.js
src/pages/Upload/OneShotAnalysis/index.js
src/pages/Upload/OneShotCopyright/index.js
src/pages/Upload/OneShotMonk/index.js

Added the one-shot license analysis, one-shot copyright and one-shot monk page.
- Created the pages for One shot.
- Added the routes.
Visit to `upload/oneShotAnalysis`, `upload/oneShotLicense`, `upload/oneShotMonk`

feat(one-shot): Added the analysis, monk and copyright page

---

src/api/auth.js
src/api/browse.js
src/api/folders.js
src/api/getFolder.js
src/api/jobs.js
src/api/search.js
src/api/sendRequest.js
src/api/upload.js
src/api/users.js

Remove the redundancy of credentials in the api.
- Remove the `credentials="include"` from all apis.
- Set the initial value of credentials to include.

fix(api): remove the redundancy of credentials

---

src/api/organizeUploads.js
src/components/Widgets/Input/index.js
src/constants/endpoints.js
src/pages/Organize/Uploads/Move/index.js
src/services/organizeUploads.js

Added the move or copy page in the `organize/uploads`
- Added the mechanism for copy and move uploads.
visit to `/organize/uploads/move`

feat(moveUpload): Added the move upload or copy upload page

---

src/api/organizeUploads.js
src/api/sendRequest.js
src/pages/Organize/Uploads/Edit/index.js
src/services/organizeUploads.js

Added the edit upload Page
Visit to `/organize/uploads/edit`

feat(edit-upload): added the edit upload page

---

.env.sample
.eslintrc.json
Dockerfile
README.md
src/constants/endpoints.js

Added support for injecting environment variables.
.env.sample -> sample env file
Dockerfile -> added support for injecting args
README.md -> modified installation steps
src/constants/endpoints.js -> using server url from env file
after creating ```.env``` file 
use the following config
```
#backend endpoint
REACT_APP_SERVER_URL=localhost/repo/api/v1
#for enabling https for backend url
REACT_APP_HTTPS=false
```
then proceed with ```yarn``` and ```yarn start```
for docker 
```
docker build \
-t fossologyui:react1.0 \
--build-arg REACT_APP_SERVER_URL="localhost/repo/api/v1" \
--build-arg REACT_APP_HTTPS="false" .
```
```docker run -p 3000:3000 fossologyui:react1.0```

feat(Infra): Introduced Config file for enviornment variables

---

src/pages/Organize/Folder/Unlink/index.js
src/pages/Organize/Uploads/Delete/index.js

Fixed the react bootstrap alerts in delete upload and unlink upload.
- Replaced the bootstrap alert with Snackbar

fix(alert): replace the bootstrap alerts with snackbars

---

.github/workflows/conflict-check.yml

Use GitHub actions to mark PRs with merge conflicts with label "has merge conflicts".
1. Create a new GitHub Action workflow which scans for dirty PRs when a merge to master happens.
Check https://github.com/fossology/fossology/pull/1993

feat(ci): Mark PRs with conflicts

---

src/api/sendRequest.js

Fixed the invalid errors, Applying airbnb style we have converted the error message to `new Error` class and it is giving invalid errors on all the requests. 
Closes #109 
Changes the new error object in `sendrequest.js`.

fix(errors): fixed the invalid errors

---

src/pages/Jobs/ScheduleAgents/index.jsx

The addition of pagination feature in browse page modified the uploaded files list function which broke the schedule jobs page.
- Fixed the select the upload to analyze component on schedule jobs page
Go to`http://localhost:3000/jobs/scheduleAgents`

fix(schedule-jobs): fix the upload list on schedule jobs page

---

src/api/licenses.js
src/api/organizeUploads.js
src/constants/endpoints.js

Sanitize URL query parameters using `query-string` library. Also the API endpoints should not have hardcoded query parameters.
- Sanitized URL query parameters
Test updated API

fix(query-params): sanitize url query parameters

---

src/Routes.jsx
src/api/browse.js
src/api/licenses.js
src/api/search.js
src/components/Header/index.jsx
src/constants/endpoints.js
src/constants/routes.js
src/pages/Organize/License/CandidateLicense/index.jsx
src/pages/Organize/License/Create/index.jsx
src/services/licenses.js

Added the create new license page for candidate.
- Added the endpoint and route for createCandidateLicense in constant folder.
- Created the function for it in services and api.
- Created the page for it.
- Shifted the listing of license page in organize into the License folder.
Visit to `/organize/license/create`

feat(license): added the candidate new license page

---

package.json
src/App.test.jsx
src/__snapshots__/App.test.jsx.snap
src/components/Title/index.jsx
src/index.jsx
yarn.lock

Fixed error in console due to the use of `react-helmet` library. Also listed as an issue in nfl/react-helmet#548
- Replaced `react-helmet` with `react-helmet-async`
Check console for error

fix(react-helmet): use react-helmet-async to fix console error

---

src/pages/Organize/Uploads/Delete/index.jsx

Code is getting broken if no upload is selected to delete.
Added the error checks in deleteUploads.
- visit to `/organize/uploads/delete`.
- click on delete button without selecting any upload to delete.

fix(errors): Added the error checks in deleteUploads

---

src/api/sendRequest.js
src/components/Header/index.jsx
src/pages/Home/index.jsx
src/shared/authHelper.js

In case of a 403 error, displayed the body of the response as a snack bar on the homepage. 
Previous discussion on #117 
- Updated logout function to accept error message as a parameter
- Updated home page to display the error message from URL query parameter
Go to `http://localhost:3000/?message=Requested%20resource%20is%20forbidden`
Or make a request which returns a 403 error code.

feat(alert): alert message on homepage for logout error

---

src/pages/Upload/File/index.jsx
src/pages/Upload/Server/index.jsx
src/pages/Upload/Vcs/index.jsx
src/shared/helper.js

fixed the user experience for uploads page since uploads page are longer than one page so on clicking the upload button user have to manually scroll to see the snackbar that whether the file is uploaded or not and we are familiar with the codebase so we knew that scrollbar appears on top right but for the first time user it may be bit confusing.
Added the `srollTo({top:0})`
Check the uploads pages.
- try uploading any file.
- or try creating any error.

fix(ux): fixed the ux of upload pages

---

package.json
src/App.test.jsx
src/__snapshots__/App.test.jsx.snap
src/components/Title/index.jsx
src/index.jsx
yarn.lock

Reverts fossology/FOSSologyUI#129
[react-helmet-async](https://github.com/staylor/react-helmet-async) is apparently licensed under [Apache-2.0](https://github.com/staylor/react-helmet-async/blob/master/LICENSE) which is not compatible with this project.

Revert "fix(react-helmet): use react-helmet-async to fix console error"

---

src/api/folders.js
src/api/organizeUploads.js
src/api/upload.js
src/components/Upload/CommonFields/UploadReuse/index.jsx
src/components/Upload/CommonFields/index.jsx
src/components/Widgets/Input/index.jsx
src/constants/endpoints.js
src/pages/Jobs/ScheduleAgents/index.jsx
src/pages/Upload/File/index.jsx
src/pages/Upload/Server/index.jsx
src/pages/Upload/Vcs/index.jsx
src/services/folders.js
src/services/organizeUploads.js

Closes #89
Closes #130  
- Added `reuse_report` and `reuse_copyright` boolean option
- Created dropdown to select reuse group from the list of accessible groups
- Displayed option to select reuse folder within the selected group (Updates whenever reuse group changes)
- Gave an option to select an upload within the previously selected folder (Updates whenever reuse group or reuse folder changes)
- Fixed prop type check error for `reuse_upload` field. A number was expected but `event.target.value` was returning a string.
Test upload from file page

feat(reuse): add all reuse options and update corresponding api

---

.env.sample
.github/workflows/deploy.yml
README.md

The [PR #8](https://github.com/Shruti3004/FOSSology-REST-API/pull/8) migrates the API version to v2 hence all subsequent requests in frontend should also be migrated to v2.
- Upgrade API versions in all places in UI
- Run fossology backend with API version v2
- Update `REACT_APP_SERVER_URL` in `.env` file
- Test if all API calls are made to `localhost/repo/api/v2`

feat(API): migrate API from v1 to v2

---

src/Routes.jsx
src/components/BrowseUploadsHeader/index.jsx
src/constants/routes.js
src/pages/BrowseUploads/Copyright/index.jsx
src/pages/BrowseUploads/Ecc/index.jsx
src/pages/BrowseUploads/FileBrowser/index.jsx
src/pages/BrowseUploads/LicenseBrowser/index.jsx
src/pages/BrowseUploads/SoftwareHeritage/index.jsx
src/styles/globalStyle.js
src/styles/theme.js

Added the pages fr browseUploads.
- Added the pages for browseUploads:
- Software Heritage
- License Browser
- File Browser
- Copyright
- ECC
- Added the browse Uploads separate header.
Visit to the following routes:
- `/browse/softwareHeritage`
- `/browse/licenseBrowser`
- `/browse/fileBrowser`
- `/browse/copyright`
- `/browse/ecc`

feat(browseUploads): added the header and pages

---

src/api/jobs.js
src/api/upload.js
src/constants/endpoints.js
src/pages/Jobs/ScheduleAgents/index.jsx
src/pages/Upload/File/index.jsx
src/pages/Upload/Url/index.jsx
src/pages/Upload/Vcs/index.jsx
src/services/jobs.js
src/services/upload.js

Fixed the scheduleAnalysis request in jobs file https://github.com/fossology/FOSSologyUI/pull/46#discussion_r662108589
- Moved the scheduleAnalysis route in jobs object.
- Shifted the scheduleAnalysis function in `api/jobs` and `services/jobs`.
- Fixed all the uploads.
- vcs 
- url
- file
- fixed the scheduleAgents in jobs.

fix(jobs): fixed the jobs api of scheduleAnalysis

---

src/components/DarkThemeToggle/DarkThemeToggle.css
src/components/DarkThemeToggle/DarkThemeToggle.jsx
src/components/Header/index.jsx
src/context/index.jsx

When someone click on the profile then only he/she can able to know about the dark theme. To create better user experience the dark theme button should be on navigation.
:- add dark theme toggle button on the navigation
:- to make the button in such a way that it would not take much space, I changed the expected UI(suggested by @GMishx )
Light theme:-
Dark theme:-
Light theme:-
Dark theme:-
Closes #173

feat: Dark theme toggle button

---

src/App.jsx
src/context/index.jsx

Signed-off-by: Devesh <deves125@gmail.com>
This bug was occurring because of a few reasons:
1. Irregularities in the naming of variables made it confusing to know what a variable actually contains.
2. `useContext` hook was implemented incorrectly. The way it was implemented is a very common mistake so it was easy to catch.
1. I fixed the `useContext` implementation.
2. Removed the line which made the page refresh.
---
1. Since the theme variable can only contain two values (`light` and `dark`), can we convert that into a boolean? That would make the logic much simpler.
2. In the context file, we are exporting a `state` variable and a `setTheme` variable which might cause confusion. I think converting the state to a boolean will solve all the confusion. The code seems too complex for such …

fix(ui): light and dark mode refresh bug fixed

---

src/pages/Admin/Users/Delete/index.jsx

This PR is in reference to the issue #195 and discussion on [preventing the deletion of default users](https://github.com/fossology/FOSSologyUI/issues/195#issuecomment-1082661293). 
- Greyed out the default users in the dropdown. 
- Added the feature to set defaults for delete user data so that the api request doesn't go invalid.
https://user-images.githubusercontent.com/71918441/160777807-61cdcf87-a77e-47ec-af3c-91afb21efa0c.mov
This PR closes #195.

feat(delete user): Disabled deletion of default users

---

src/constants/constants.js
src/pages/Search/index.jsx

Constants exported from the search component
`pages/search/index.js`
partly fixes: #108 
Run the server and go to the search page to check it's functionality.

fix(update): Exported constants from the search component

---

src/api/sendRequest.js
src/api/sendRequest.test.js
src/api/upload.js
src/api/upload.test.js
src/api/users.js
src/api/users.test.js

This error appears in the console when we navigate to the delete user page.
This PR concerns with the fact that fossology API now doesn't require credentials to work and has been removed from the backend. So, the header needs to be removed from the frontend as well.
~~`credentials: "includes"`~~
`yarn test`

refactor(api): removed credentials from api request module 

---

src/constants/constants.js
src/pages/Search/index.jsx
src/pages/Upload/File/index.jsx
src/pages/Upload/ImportReport/index.jsx
src/pages/Upload/Server/index.jsx
src/pages/Upload/Url/index.jsx
src/pages/Upload/Vcs/index.jsx

Exported the constants that were being used in the Upload directory and reused them where ever same constants were being used.
`src/pages/upload`
Run the Front-end with the latest backend and try to upload files using different methods
Fixes #108

Exported constants from upload directory and reused them

---

src/components/Widgets/Input/index.jsx

This PR is in reference to the issue #167 . A warning in the console stated an error like below,
```
Warning: Select elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled select element and remove one of these props. More info: https://reactjs.org/link/controlled-components
select
```
This occurs when we try to use `value` and `defaultValue` prop inside a select tag simultaneously.
The solution is to remove one of the `value` or `defaultValue` prop.
Note: This PR also have the fixes for [undefined value for currentGroup in local storage](https://github.com/fossology/FOSSologyUI/pull/179#issuecomment-1073585315)
This PR closes #167 .

fix (components/widgets/input): Warning while loading delete user page

---

src/Routes.jsx
src/components/Header/index.jsx
src/constants/constants.js
src/constants/routes.js
src/pages/Admin/Mantainance/index.jsx

Signed-off-by: dushimsam <dushsam100@gmail.com>
Implemented the maintenance page from the Admin section. The page is on the route `/admin/mantainance`
1. Created a new directory ,`src/pages/admin/Mantainance/index.jsx`
2. Imported and added the new page in the `src/Routes.jsx` as a part of `AdminLayout`
3. Added a new navigation dropdown Item as a part of the admin dropdowns.
4.  Added the route and initial field values for the new page in `src/constants/routes.js`.
1. Go in the project's main directory.
2. run command `npm start`
3. Visit the page at `http://localhost:PORT/admin/mantainance` 
4. You should see something looking like this 
##Screenshots
Fixes #227 
@shaheemazmalmmd @GMishx

feat(ui): implementation of mantainance page on the admin section

---

src/Routes.jsx
src/api/upload.js
src/components/BrowseUploadsHeader/index.jsx
src/constants/endpoints.js
src/pages/Browse/index.jsx
src/pages/BrowseUploads/LicenseBrowser/index.jsx
src/services/upload.js

Added the License Browser page.
- Added the license prowser page.
- Added the api endpoints for summary and license of the uploads.
- Integrated the api for uploads summary api.
- Completed the function for getting license in api and services.
- called the function in license browser page.
Visit to `/browse` and click to any of the uploads.

feat(license-browser): added the license browser page

---

src/Routes.jsx
src/api/users.js
src/components/Header/index.jsx
src/components/Upload/CommonFields/AccessLevel/index.jsx
src/components/Upload/CommonFields/index.jsx
src/constants/constants.js
src/constants/endpoints.js
src/constants/messages.js
src/constants/routes.js
src/pages/Admin/Users/Add/index.jsx
src/services/users.js

Signed-off-by: Krishna Mahato <krishhtrishh9304@gmail.com>
Ui and API Implementation is done for the `Add User page`.
https://user-images.githubusercontent.com/71918441/174468938-a0553bff-3e0d-4428-b62c-831ed4328767.mp4
In the UI Go to `Admin > Users > Add User`
- Install the api from this PR https://github.com/fossology/fossology/pull/2256 in the fossology backend.
This closes #224 .
PTAL : @shaheemazmalmmd @sjha2048 @GMishx @Shruti3004

feature(ui): ui and formdata implementation for the `add user` page

---

src/pages/BrowseUploads/LicenseBrowser/index.jsx

Made changes in the request header of the API that was being called in order to show the licenses. Also enabled the field for edited responses. 
Changes made in : `BrowserUploads/LicenseBrowser/index.jsx`
Start the server and visit a License browser page of a repository to see the updates.
PTAL: @GMishx @Shruti3004 @shaheemazmalmmd

fix(licenses): header fixed and limit for responses removed

---

.gitignore
package.json
src/App.jsx
src/Routes.jsx
src/api/groups.js
src/components/Modals/DeleteConfirmation/index.jsx
src/components/Widgets/Button/index.jsx
src/constants/endpoints.js
src/constants/messages.js
src/pages/Admin/Group/Delete/index.jsx
src/services/groups.js
yarn.lock

Signed-off-by: dushimsam <dushsam@gmail.com>
Added delete group page.
1. Added a new file [src/pages/Admin/Group/Delete/index.jsx](https://github.com/fossology/FOSSologyUI/compare/main...dushimsam:dushimsam/feat/admin/delete-group?expand=1#diff-c6b9aa81b2449d23ccce198771cd8a82eaa0c2cb79471649612205743a6c8bd4) for the UI feature.
2. Introduced a new route in `src/Routes.jsx`
3. Introduced new API callers for the UI integration.
4. Added a new constant message for successful group deletion.
1. Go to the project's main directory.
2. run command `npm start`
3. Visit the page at `http://localhost:PORT/admin/group/delete` 
4. You are going to see a list of deletable groups which you can select.
5. Select the group you wish to delete then press `Delete` button.
Fixes …

feat(ui): added delete group page

---

src/Routes.jsx
src/api/jobs.js
src/components/Header/index.jsx
src/constants/constants.js
src/constants/endpoints.js
src/constants/routes.js
src/pages/Browse/index.jsx
src/pages/Upload/ImportReport/index.jsx
src/services/jobs.js

Signed-off-by: Krishna Mahato <krishhtrishh9304@gmail.com>
Importing an existing report to an upload functionality is now implemented. 
The page is available from 2 places in the UI
1. In the navbar, Go to `Upload > Import Report`.
2. Directly from the browse page. Choose the upload and select `Import Report` option from the actions dropdown.
Tasks completed ---
https://user-images.githubusercontent.com/71918441/190134484-0aa5ee23-632c-4724-8467-b50fef1bba21.mp4
This fixes #264 .
cc: @GMishx @Shruti3004 @shaheemazmalmmd

feat(ui): Added logical components to the report import page and Integrated the API

---

README.md

Running the below command while setting up the project on local machine, I got some error related to [this](https://stackoverflow.com/questions/64131790/yarn-add-raise-error-missing-list-of-packages-to-add-to-your-project).
```zsh
docker-compose -f docker-compose.dev.yml exec -w /usr/src/fossologyui fossologyui_server yarn add --save <package name> #Install npm package for react-dev-server
```
It says that --save flag is unsupported by yarn.
In the Readme.md file in the root directory, removed the --save flag and it worked.

Unsupported --save during npm packages installation removed in Readme.md
